# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDockWidget, QFrame, QGridLayout,
    QGroupBox, QHBoxLayout, QLCDNumber, QLabel,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QTextBrowser,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1324, 822)
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 255, 127, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Light, brush1)
        brush2 = QBrush(QColor(255, 255, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush1)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush1)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush3 = QBrush(QColor(255, 255, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush3)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush4 = QBrush(QColor(216, 248, 255, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush4)
        brush5 = QBrush(QColor(199, 199, 199, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        brush6 = QBrush(QColor(147, 163, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush6)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush8 = QBrush(QColor(240, 240, 240, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        brush9 = QBrush(QColor(227, 227, 227, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush9)
        brush10 = QBrush(QColor(160, 160, 160, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush10)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush10)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush8)
        brush11 = QBrush(QColor(105, 105, 105, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush11)
        brush12 = QBrush(QColor(245, 245, 245, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush12)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush12)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDockOptions(QMainWindow.AllowNestedDocks|QMainWindow.AllowTabbedDocks|QMainWindow.AnimatedDocks)
        self.actionConnect = QAction(MainWindow)
        self.actionConnect.setObjectName(u"actionConnect")
        self.actionDisconnect = QAction(MainWindow)
        self.actionDisconnect.setObjectName(u"actionDisconnect")
        self.actionTest_Connection = QAction(MainWindow)
        self.actionTest_Connection.setObjectName(u"actionTest_Connection")
        self.actionPORT = QAction(MainWindow)
        self.actionPORT.setObjectName(u"actionPORT")
        self.actionIP_2 = QAction(MainWindow)
        self.actionIP_2.setObjectName(u"actionIP_2")
        self.actionPORT_2 = QAction(MainWindow)
        self.actionPORT_2.setObjectName(u"actionPORT_2")
        self.actionIP_3 = QAction(MainWindow)
        self.actionIP_3.setObjectName(u"actionIP_3")
        self.actionPORT_3 = QAction(MainWindow)
        self.actionPORT_3.setObjectName(u"actionPORT_3")
        self.actionTCP = QAction(MainWindow)
        self.actionTCP.setObjectName(u"actionTCP")
        self.actionTCP.setCheckable(True)
        self.actionTCP.setChecked(True)
        self.actionStatus = QAction(MainWindow)
        self.actionStatus.setObjectName(u"actionStatus")
        self.actionSpeed = QAction(MainWindow)
        self.actionSpeed.setObjectName(u"actionSpeed")
        self.actionXbox_Controller = QAction(MainWindow)
        self.actionXbox_Controller.setObjectName(u"actionXbox_Controller")
        self.actionXbox_Controller.setCheckable(True)
        self.actionTest_Robot_Motors = QAction(MainWindow)
        self.actionTest_Robot_Motors.setObjectName(u"actionTest_Robot_Motors")
        self.actionOverwrite = QAction(MainWindow)
        self.actionOverwrite.setObjectName(u"actionOverwrite")
        self.actionOverwrite.setCheckable(True)
        self.actionOpen_log_file = QAction(MainWindow)
        self.actionOpen_log_file.setObjectName(u"actionOpen_log_file")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1324, 26))
        palette1 = QPalette()
        brush13 = QBrush(QColor(0, 85, 0, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush13)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush)
        brush14 = QBrush(QColor(208, 208, 208, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush14)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush12)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush13)
        brush15 = QBrush(QColor(161, 161, 161, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush15)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush12)
        self.menubar.setPalette(palette1)
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuConnection_2 = QMenu(self.menuSettings)
        self.menuConnection_2.setObjectName(u"menuConnection_2")
        self.menuMotors = QMenu(self.menuSettings)
        self.menuMotors.setObjectName(u"menuMotors")
        self.menuConnection = QMenu(self.menubar)
        self.menuConnection.setObjectName(u"menuConnection")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidgetControls = QDockWidget(MainWindow)
        self.dockWidgetControls.setObjectName(u"dockWidgetControls")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetControls.sizePolicy().hasHeightForWidth())
        self.dockWidgetControls.setSizePolicy(sizePolicy)
        self.dockWidgetControls.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.gridLayout_2 = QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.tabWidget = QTabWidget(self.dockWidgetContents_2)
        self.tabWidget.setObjectName(u"tabWidget")
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.gridLayout_3 = QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.frame = QFrame(self.tab)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        font = QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.label)

        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setFrameShape(QFrame.Box)
        self.label_5.setFrameShadow(QFrame.Plain)

        self.verticalLayout.addWidget(self.label_5)

        self.pushButton_2 = QPushButton(self.frame)
        self.pushButton_2.setObjectName(u"pushButton_2")

        self.verticalLayout.addWidget(self.pushButton_2)


        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)

        self.groupBoxController = QGroupBox(self.tab)
        self.groupBoxController.setObjectName(u"groupBoxController")
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.groupBoxController.sizePolicy().hasHeightForWidth())
        self.groupBoxController.setSizePolicy(sizePolicy1)
        self.groupBoxController.setAlignment(Qt.AlignCenter)
        self.verticalLayout_7 = QVBoxLayout(self.groupBoxController)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.pushButton_3 = QPushButton(self.groupBoxController)
        self.pushButton_3.setObjectName(u"pushButton_3")

        self.verticalLayout_7.addWidget(self.pushButton_3)

        self.pushButton_5 = QPushButton(self.groupBoxController)
        self.pushButton_5.setObjectName(u"pushButton_5")

        self.verticalLayout_7.addWidget(self.pushButton_5)


        self.gridLayout_3.addWidget(self.groupBoxController, 0, 2, 1, 1)

        self.frame_3 = QFrame(self.tab)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.label_3 = QLabel(self.frame_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_3)

        self.label_7 = QLabel(self.frame_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setFrameShape(QFrame.Box)

        self.verticalLayout_3.addWidget(self.label_7)

        self.pushButton = QPushButton(self.frame_3)
        self.pushButton.setObjectName(u"pushButton")

        self.verticalLayout_3.addWidget(self.pushButton)


        self.gridLayout_3.addWidget(self.frame_3, 0, 3, 1, 1)

        self.frame_2 = QFrame(self.tab)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font)
        self.label_2.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.label_2)

        self.label_6 = QLabel(self.frame_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setFrameShape(QFrame.Box)
        self.label_6.setFrameShadow(QFrame.Plain)

        self.verticalLayout_2.addWidget(self.label_6)

        self.pushButton_4 = QPushButton(self.frame_2)
        self.pushButton_4.setObjectName(u"pushButton_4")

        self.verticalLayout_2.addWidget(self.pushButton_4)


        self.gridLayout_3.addWidget(self.frame_2, 0, 1, 1, 1)

        self.frame_4 = QFrame(self.tab)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.label_4 = QLabel(self.frame_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QFrame.NoFrame)
        self.label_4.setFrameShadow(QFrame.Plain)
        self.label_4.setAlignment(Qt.AlignCenter)

        self.verticalLayout_4.addWidget(self.label_4)

        self.label_8 = QLabel(self.frame_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setFrameShape(QFrame.Box)

        self.verticalLayout_4.addWidget(self.label_8)

        self.pushButton_6 = QPushButton(self.frame_4)
        self.pushButton_6.setObjectName(u"pushButton_6")

        self.verticalLayout_4.addWidget(self.pushButton_6)


        self.gridLayout_3.addWidget(self.frame_4, 0, 4, 1, 1)

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.horizontalLayout_2 = QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.groupBox = QGroupBox(self.tab_2)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setAlignment(Qt.AlignCenter)
        self.groupBox.setCheckable(False)
        self.verticalLayout_10 = QVBoxLayout(self.groupBox)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.pushButton_9 = QPushButton(self.groupBox)
        self.pushButton_9.setObjectName(u"pushButton_9")

        self.verticalLayout_10.addWidget(self.pushButton_9)

        self.pushButtonPing = QPushButton(self.groupBox)
        self.pushButtonPing.setObjectName(u"pushButtonPing")

        self.verticalLayout_10.addWidget(self.pushButtonPing)


        self.horizontalLayout_2.addWidget(self.groupBox)

        self.groupBoxTest = QGroupBox(self.tab_2)
        self.groupBoxTest.setObjectName(u"groupBoxTest")
        self.groupBoxTest.setAlignment(Qt.AlignCenter)
        self.horizontalLayout_4 = QHBoxLayout(self.groupBoxTest)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.pushButtonTest1 = QPushButton(self.groupBoxTest)
        self.pushButtonTest1.setObjectName(u"pushButtonTest1")

        self.horizontalLayout_4.addWidget(self.pushButtonTest1)


        self.horizontalLayout_2.addWidget(self.groupBoxTest)

        self.groupBoxTest_2 = QGroupBox(self.tab_2)
        self.groupBoxTest_2.setObjectName(u"groupBoxTest_2")
        self.groupBoxTest_2.setAlignment(Qt.AlignCenter)
        self.verticalLayout_8 = QVBoxLayout(self.groupBoxTest_2)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.lcdNumberInQue = QLCDNumber(self.groupBoxTest_2)
        self.lcdNumberInQue.setObjectName(u"lcdNumberInQue")

        self.verticalLayout_8.addWidget(self.lcdNumberInQue)


        self.horizontalLayout_2.addWidget(self.groupBoxTest_2)

        self.groupBoxTest_3 = QGroupBox(self.tab_2)
        self.groupBoxTest_3.setObjectName(u"groupBoxTest_3")
        self.groupBoxTest_3.setAlignment(Qt.AlignCenter)
        self.verticalLayout_9 = QVBoxLayout(self.groupBoxTest_3)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.lcdNumberOutQue = QLCDNumber(self.groupBoxTest_3)
        self.lcdNumberOutQue.setObjectName(u"lcdNumberOutQue")

        self.verticalLayout_9.addWidget(self.lcdNumberOutQue)


        self.horizontalLayout_2.addWidget(self.groupBoxTest_3)

        self.tabWidget.addTab(self.tab_2, "")

        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 2, 2)

        self.dockWidgetControls.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(Qt.BottomDockWidgetArea, self.dockWidgetControls)
        self.dockWidgetCamera = QDockWidget(MainWindow)
        self.dockWidgetCamera.setObjectName(u"dockWidgetCamera")
        sizePolicy1.setHeightForWidth(self.dockWidgetCamera.sizePolicy().hasHeightForWidth())
        self.dockWidgetCamera.setSizePolicy(sizePolicy1)
        self.dockWidgetCamera.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.verticalLayout_5 = QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.groupBox_camera = QGroupBox(self.dockWidgetContents)
        self.groupBox_camera.setObjectName(u"groupBox_camera")
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.groupBox_camera.sizePolicy().hasHeightForWidth())
        self.groupBox_camera.setSizePolicy(sizePolicy2)
        self.groupBox_camera.setMaximumSize(QSize(16777215, 60))
        self.horizontalLayout = QHBoxLayout(self.groupBox_camera)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label_fps = QLabel(self.groupBox_camera)
        self.label_fps.setObjectName(u"label_fps")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.label_fps.sizePolicy().hasHeightForWidth())
        self.label_fps.setSizePolicy(sizePolicy3)

        self.horizontalLayout.addWidget(self.label_fps)

        self.pushButton_open = QPushButton(self.groupBox_camera)
        self.pushButton_open.setObjectName(u"pushButton_open")
        sizePolicy3.setHeightForWidth(self.pushButton_open.sizePolicy().hasHeightForWidth())
        self.pushButton_open.setSizePolicy(sizePolicy3)

        self.horizontalLayout.addWidget(self.pushButton_open)


        self.verticalLayout_5.addWidget(self.groupBox_camera)

        self.label_camera = QLabel(self.dockWidgetContents)
        self.label_camera.setObjectName(u"label_camera")
        sizePolicy3.setHeightForWidth(self.label_camera.sizePolicy().hasHeightForWidth())
        self.label_camera.setSizePolicy(sizePolicy3)
        self.label_camera.setScaledContents(True)

        self.verticalLayout_5.addWidget(self.label_camera)

        self.dockWidgetCamera.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.TopDockWidgetArea, self.dockWidgetCamera)
        self.dockWidget_2 = QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName(u"dockWidget_2")
        self.dockWidget_2.setFloating(False)
        self.dockWidget_2.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.dockWidgetContents_4 = QWidget()
        self.dockWidgetContents_4.setObjectName(u"dockWidgetContents_4")
        self.verticalLayout_6 = QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.textBrowser_log = QTextBrowser(self.dockWidgetContents_4)
        self.textBrowser_log.setObjectName(u"textBrowser_log")

        self.verticalLayout_6.addWidget(self.textBrowser_log)

        self.dockWidget_2.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(Qt.TopDockWidgetArea, self.dockWidget_2)
        self.dockWidget_2.raise_()
        self.dockWidgetCamera.raise_()
        QWidget.setTabOrder(self.pushButton_2, self.pushButton_4)
        QWidget.setTabOrder(self.pushButton_4, self.pushButton_3)
        QWidget.setTabOrder(self.pushButton_3, self.pushButton_5)
        QWidget.setTabOrder(self.pushButton_5, self.pushButton)
        QWidget.setTabOrder(self.pushButton, self.pushButton_6)

        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuConnection.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menuSettings.addAction(self.menuConnection_2.menuAction())
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.menuMotors.menuAction())
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionOpen_log_file)
        self.menuConnection_2.addAction(self.actionIP_3)
        self.menuConnection_2.addAction(self.actionPORT_3)
        self.menuConnection_2.addAction(self.actionTCP)
        self.menuMotors.addAction(self.actionSpeed)
        self.menuConnection.addAction(self.actionStatus)
        self.menuConnection.addSeparator()
        self.menuConnection.addAction(self.actionConnect)
        self.menuConnection.addAction(self.actionDisconnect)
        self.menuConnection.addSeparator()
        self.menuConnection.addAction(self.actionTest_Connection)
        self.menuTools.addAction(self.actionXbox_Controller)
        self.menuTools.addAction(self.actionTest_Robot_Motors)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionConnect.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.actionDisconnect.setText(QCoreApplication.translate("MainWindow", u"Disconnect", None))
        self.actionTest_Connection.setText(QCoreApplication.translate("MainWindow", u"Test Connection", None))
        self.actionPORT.setText(QCoreApplication.translate("MainWindow", u"PORT = ", None))
        self.actionIP_2.setText(QCoreApplication.translate("MainWindow", u"IP = ", None))
        self.actionPORT_2.setText(QCoreApplication.translate("MainWindow", u"PORT = ", None))
        self.actionIP_3.setText(QCoreApplication.translate("MainWindow", u"IP = ", None))
        self.actionPORT_3.setText(QCoreApplication.translate("MainWindow", u"PORT = ", None))
        self.actionTCP.setText(QCoreApplication.translate("MainWindow", u"TCP", None))
        self.actionStatus.setText(QCoreApplication.translate("MainWindow", u"Status:", None))
        self.actionSpeed.setText(QCoreApplication.translate("MainWindow", u"Speed = ", None))
        self.actionXbox_Controller.setText(QCoreApplication.translate("MainWindow", u"Xbox Controller Input", None))
        self.actionTest_Robot_Motors.setText(QCoreApplication.translate("MainWindow", u"Test Robot Motors", None))
        self.actionOverwrite.setText(QCoreApplication.translate("MainWindow", u"Overwrite?", None))
#if QT_CONFIG(tooltip)
        self.actionOverwrite.setToolTip(QCoreApplication.translate("MainWindow", u"Overwrite log file on new session?", None))
#endif // QT_CONFIG(tooltip)
        self.actionOpen_log_file.setText(QCoreApplication.translate("MainWindow", u"Open log file", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.menuConnection_2.setTitle(QCoreApplication.translate("MainWindow", u"Connection", None))
        self.menuMotors.setTitle(QCoreApplication.translate("MainWindow", u"Motors", None))
        self.menuConnection.setTitle(QCoreApplication.translate("MainWindow", u"Connection", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.dockWidgetControls.setWindowTitle(QCoreApplication.translate("MainWindow", u"Controls", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"X-Ray Screen", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Status: UNKNOWN", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"DEPLOY SCREEN", None))
        self.groupBoxController.setTitle(QCoreApplication.translate("MainWindow", u"Controller: INACTIVE", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"ACTIVATE XBOX CONTROLLER", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"ACTIVATE KEYBOARD CONTROLLER", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Robot Movement", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Status: UNKNOWN", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"MOVE ROBOT", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"X-Ray Source", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Status: UNKNOWN", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"DEPLOY SOURCE", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Camera Movement", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Status: UNKNOWN", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"MOVE CAMERA", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Robot", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Server Status: DISCONNECTED", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"CONNECT", None))
        self.pushButtonPing.setText(QCoreApplication.translate("MainWindow", u"PING", None))
        self.groupBoxTest.setTitle(QCoreApplication.translate("MainWindow", u"Testing", None))
        self.pushButtonTest1.setText(QCoreApplication.translate("MainWindow", u"TEST 1", None))
        self.groupBoxTest_2.setTitle(QCoreApplication.translate("MainWindow", u"Incoming Queue", None))
        self.groupBoxTest_3.setTitle(QCoreApplication.translate("MainWindow", u"Outgoing Queue", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Server", None))
        self.dockWidgetCamera.setWindowTitle(QCoreApplication.translate("MainWindow", u"Camera Feed", None))
        self.groupBox_camera.setTitle("")
        self.label_fps.setText(QCoreApplication.translate("MainWindow", u"0 FPS", None))
        self.pushButton_open.setText(QCoreApplication.translate("MainWindow", u"Open Feed", None))
        self.label_camera.setText(QCoreApplication.translate("MainWindow", u"camera", None))
        self.dockWidget_2.setWindowTitle(QCoreApplication.translate("MainWindow", u"Console", None))
    # retranslateUi

